### ISSUE TITLE
Comparisons to Dynamic Values

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/atef#100]
## Expected Behavior

It should be possible to add comparisons to PV values and signal values rather than just to static values.

## Current Behavior

All comparisons are currently to static values.

## Possible Solution

One way to handle this is to allow any of the value fields to hold `str` types that hold references to other data.
For example, we could borrow the pydm channel syntax and interpret something like `"ca://MY:PVNAME"` as "use channel access to get MY:PVNAME and use the value as the comparison." We could refer to signals as `"sig://my_signame"` or use other more creative addressing as appropriate.

## Context

Andrew has been working on some laser system automated check setups and raised to our attention that this is an important feature.

**Comment by ZLLentz** [comment]
After mulling it over at the Alpine Inn, I'm fully on board. Sitting in the `pydm` box is going to be annoying (and, truthfully, maybe `pydm` should consider extending the channel definition itself instead of filling up increasingly elaborate strings).

There must be a clean implementation for this via creating a `DynamicValue` dataclass parallel to `Value`, either completely separate or inheriting from `Value`. There are some wrinkles with the proliferation of this to things like the > comparisons or the range comparisons which don't use `Value` at all right now but need to start doing so.

**Comment by tangkong** [comment]
Looking into resurrecting this effort, before moving on to other Active checkout steps and features.  We should refer back to #111 as work continues, but the GUI has moved considerably since its last commit (Jul 2022), and we'll have to do more than merge the diff.

**Comment by tangkong** [comment]
closed by #184
