### ISSUE TITLE
No Scroll Option for "Add Checklist" Page

### ISSUE THREAD

**Issue by liggett2820** [pcdshub/atef#103]
## Expected Behavior
When adding checklists, there should be a point where a scroller comes up and allows for more room for checklists.

## Current Behavior
When creating checklists, the window just expands until it fills the whole screen, limiting the amount of checklists a configuration can have.

## Possible Solution
Add a scrolling feature to this page to allow for more checklists.

## Steps to Reproduce (for bugs)

1. When creating a configuration, click on "Add Checklist"
2. Repeat 1. until the page fills the window.
3. At this point, the user is no longer able to add more configurations.

## Context
This limits the size of each configuration and forces the checks to be split up between multiple configurations.

## Your Environment
source pcds_conda
My repo: /cds/home/l/liggett1/atef

**Comment by ZLLentz** [comment]
Scrollbars are pretty easy to add- thank you for bringing this up.
