### ISSUE TITLE
Effectiveness of "Lock/Unlock Editing" Button

### ISSUE THREAD

**Issue by liggett2820** [pcdshub/atef#104]
## Expected Behavior
When activated, the user should not be able to change anything about the configuration.

## Current Behavior
There is a loophole to this by selecting what to edit from the side menu, bypassing the lock/unlock editing button

## Possible Solution
Have the button affect the whole configuration, no matter what screen is open.

Perhaps adding a password protection to unlock the editing.

## Steps to Reproduce (for bugs)

1. When creating a PV config, click on the configuration name in the side menu.
2. This will bring you to the checklist page, which will also allow you to edit the name and description of the PV.

## Context
This problem essentially bypasses the whole button in general and prevents it from being used as originally intended.

## Your Environment
source pcds_conda
My repo: /cds/home/l/liggett1/atef

**Comment by ZLLentz** [comment]
Similar to #46
