### ISSUE TITLE
Multiple checklists for device configs

### ISSUE THREAD

**Issue by liggett2820** [pcdshub/atef#120]
## Expected Behavior
Should be able to assign different checklists to different devices within a device config.

## Current Behavior
One checklist per device config only goes through that one checklist for all of the devices on the device config.

Currently each device config assumes that all devices are the same type. When trying to group devices by MODS TILEs, the checklists don't support different device types.

## Possible Solution
Allow multiple checklists per device config and be able to assign them to different devices.

## Steps to Reproduce (for bugs)

![Screen Shot 2022-07-20 at 2 01 44 PM](https://user-images.githubusercontent.com/108372247/180082558-e0588619-5ba4-4be0-943c-8ca9d3c5f6af.png)

## Context
Need to be able to check different devices within each TILE.

## Your Environment
source pcds_conda
my repo: /cds/home/l/liggett1/atef

**Comment by ZLLentz** [comment]
Are you asking for the checklists to be assignable to only subsets of devices in the config? I think we were imagining that this use case would be covered by separate "device config" objects, but I see that you're using "device config" as an organizational header for a TILE.

Does that mean that we're missing one hierarchy level for grouping device configs?
Or maybe we need to have a different "view" of the config so it can be seen per TILE or other organizational unit?
