### ISSUE TITLE
New files created in atef config do not save as .json files

### ISSUE THREAD

**Issue by liggett2820** [pcdshub/atef#122]
## Expected Behavior
All files created in atef config should be saved as .json files.

## Current Behavior
Files created and saved in atef config do not save as .json files.

## Possible Solution
Have files created and saved in atef config save as .json files.

## Steps to Reproduce (for bugs)

1. Open atef config
2. create new file
3. save file
4. file doesn't save as .json file

## Context
atef won't find the file you saved before when searching for the file to open in atef config

## Your Environment
source pcds_conda
my repo: /cds/home/l/liggett1/atef/

**Comment by ZLLentz** [comment]
I don't think this is quite correct. Ken and I never came to a conclusion over whether to use json or yaml files and were tentatively intending to support both formats.

**Comment by ZLLentz** [comment]
`yaml` tends to be more human-friendly but slower to open

**Comment by liggett2820** [comment]
when trying to open a file within atef config, it only looks for files ending in .json. When saving a new file in atef config, it says that it will save it as a .json file but it doesn't


(when saving)
<img width="812" alt="Screen Shot 2022-07-27 at 2 32 54 PM" src="https://user-images.githubusercontent.com/108372247/181376356-b3523645-f06c-4157-bf2c-3c192d634b25.png">

(when opening)
<img width="812" alt="Screen Shot 2022-07-27 at 2 34 52 PM" src="https://user-images.githubusercontent.com/108372247/181376691-876eaba5-f20b-4301-a712-a22381fad672.png">

**Comment by ZLLentz** [comment]
Sorry, can you explain more precisely what you mean by "it says that it will save it as a .json file but it doesn't"? Is it the file extension missing or something else?

It would be a bit incredible if this source code snippit failed to create a json file: https://github.com/pcdshub/atef/blob/a7c875f7f31c81a00eb174e43113866f05c682ec/atef/widgets/config.py#L190

**Comment by liggett2820** [comment]
yeah when saving a newly created file, it does not add on the file extension (in this case, .json)

**Comment by ZLLentz** [comment]
Got it, we can fix this. I'm super surprised that the built-in qt file dialog doesn't just... do it for us, especially since it has an argument for filtering file types that I'm using. I guess we just check if the extension is present and add it to the filename before writing the output.

**Comment by liggett2820** [comment]
ok I know how to fix it. @ZLLentz can you assign me to this bug?

**Comment by liggett2820** [comment]
so it looks like I don't have permission to push my bug fix. can someone just real quick change line 189 from the same `config.py` file that Zach mentioned above from `with open (filename, 'w') as fd:` to `with open (filename+'.json', 'w') as fd:`

**Comment by klauer** [comment]
@liggett2820, please follow the forking model described here to open a pull request with your fix: https://pcdshub.github.io/development.html

**Comment by liggett2820** [comment]
I tried that and it said `remote: Permission to pcdshub/atef.git denied to liggett2820.
fatal: unable to access 'https://github.com/pcdshub/atef.git/': The requested URL returned error: 403` GitHub won't let me open a pull request for this bug either

**Comment by klauer** [comment]
You should be pushing to your fork and not to `pcdshub`. 
Check `git remote -v` and ensure you are pushing your branch to `liggett2820/atef`.

**Comment by liggett2820** [comment]
How do I change where I push to? And GitHub is unable to find the branch I created.

**Comment by klauer** [comment]
Let's move this over to Slack #atef and we can try to help you there
