### ISSUE TITLE
BUG: Problematic Relative Tolerance in ATEF Comparison Settings 

### ISSUE THREAD

**Issue by omniAron** [pcdshub/atef#128]
Was using atef to set the comparison values of a working environmental sensor using the CRIX injection tile and the relative tolerance was set to a value, set to zero without entering, and the relative tolerance indicator would update to 0 despite being equal to the previous set value.

## Expected Behavior
Deleting tolerance value should set the value equal to zero.

## Current Behavior
Setting the relative tolerance value to empty will not update the value to zero.

## Possible Solution
Unsure

## Steps to Reproduce 
![Screenshot from 2022-10-04 17-12-00](https://user-images.githubusercontent.com/97323386/193952970-d740a0f6-6f31-4207-8eaa-001a47ff3419.png)
(for bugs)

## Context
Minor inconvenience

## Your Environment
source pcds_conda

**Comment by ZLLentz** [comment]
Good catch, I wonder if there are other fields like this where there isn't any data handling on "empty" text entries.
