### ISSUE TITLE
Start procedure representation + widgets

### ISSUE THREAD

**Issue by klauer** [pcdshub/atef#20]
Ref https://github.com/pcdshub/atef/discussions/16

* Procedure steps and groups thereof
* Procedure steps should be implemented as dataclasses with self-describing type hints
* Steps should be serializable
* Steps should be viewable as custom atef widgets
* Procedure should be viewable as a scrollable page of sorts (familiar to web browser users + typhos device displays)

For starters:
* Description: narrative - describe what to do
* Code: run some arbitrary code (locally? on queue server if possible?)
* Open a typhos display (by happi name / class+kwargs)
* Open a pydm display
* Show a device configuration / comparison (pass/fail criteria could be used to continue)
* Run a bluesky plan (with some/all arguments customizable)
* Group: group any and all of the above

To consider:
* Per-step check box for user to acknowledge step completion?

(Separate issues to be made for: report generation tools, qserver stuff, ...)

**Comment by tangkong** [comment]
I think this is technically closed, I'll open an issue for the screen-steps.  (wow it's been 2 years 👀 )
