### ISSUE TITLE
Enum values are not checked fully correctly

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/atef#200]
## Expected Behavior

If I make a check that runs against an enum value, it should be converted to the enum string before being compared.

## Current Behavior

Enum values are kept as integers for the comparison:

![image](https://github.com/pcdshub/atef/assets/10647860/1e87f0c6-206d-40e1-8673-2b3e3f325efa)

## Possible Solution

I guess we need to convert these or store both the int and the enum when we get the values

## Steps to Reproduce (for bugs)

1. make a check against an enum
2. run the checkout

## Context

I was click testing #198 when I noticed this

## Your Environment

pcds-5.7.3 + atef from #198

**Comment by klauer** [comment]
I _think_ the idea was to set `string=True` on the channel for enum comparison back in the day

That said atef should be smart enough to check both

**Comment by ZLLentz** [comment]
> I think the idea was to set string=True on the channel

I think this is correct- maybe the real thing here is that the "string" param is a bit outdated now that the input is typed...

**Comment by ZLLentz** [comment]
Or maybe we can flip "string" to true automatically if you're comparing to an enum or string... Lots of ways to handle this!
