### ISSUE TITLE
BUG: atef still attempts to open a file if it cannot be loaded

### ISSUE THREAD

**Issue by tangkong** [pcdshub/atef#202]
## Expected Behavior
Atef should just say it can't open the file

## Current Behavior
Attempts to open a new tab with data that doesn't exist

## Possible Solution
Show a message box and return if the deserialization fails

## Steps to Reproduce (for bugs)
1. Open an old or invalid config

## Context
Was opening old LAS configs

## Your Environment
atef v1.0.0, pcds-5.7.3

**Comment by klauer** [comment]
Did that conversion script I wrote actually work? I don't think we ever even tried it
Ref https://github.com/pcdshub/atef/blob/master/scripts/converter_v0.py
