### ISSUE TITLE
BUG: QPainter divide by zero error

### ISSUE THREAD

**Issue by tangkong** [pcdshub/atef#210]
## Expected Behavior
no bug

## Current Behavior
Sometimes we get this divide by zero float error.  This seems to have nothing to do with the control layer portion of the app, but more with qt/pydm

I'm suspicious of the missing arrow in the ActionRowWidget, but didn't find any immediate issues in the environment

## Steps to Reproduce (for bugs)
I've been unable to reproduce this remotely.. very confusing

## Context
as tmoopr on tmo-monitor, running atef config

![image](https://github.com/pcdshub/atef/assets/35379409/2d94c086-a703-4a94-bf75-e6542f19e401)
![image](https://github.com/pcdshub/atef/assets/35379409/730aea04-a83f-4cb7-90a7-206b2509c7af)

## Your Environment
pcds_conda -> dev_conda, atef master @ 8212d7f24, pydm 1.19.1

**Comment by ZLLentz** [comment]
Looks like this happens if your arrow is zero length
https://github.com/slaclab/pydm/blob/f3fa59e95eb2b3c68511920d5c814b96974b4f70/pydm/widgets/drawing.py#L478-L484

**Comment by tangkong** [comment]
I suppose a simple minimumSize setting might help here, though I can squeeze the arrow out of existence and not experience the same errors 🤔 

<img width="521" alt="image" src="https://github.com/pcdshub/atef/assets/35379409/201984f5-0789-4082-ae84-41d4dd5852b4">

**Comment by ZLLentz** [comment]
I wonder under what cases a widget gets a paint event from qt- and further, under what cases a zero-size widget gets a paint event from qt.
Even if we can fix it ourselves here with some finagling maybe I/we can submit a basic pydm pr

**Comment by tangkong** [comment]
Locally I was able to reproduce this if I initialized a view where the arrow was hidden (length=0), then slowly expanded the window until the arrow appeared.  If you are too quick about expanding / contracting the window, it's possible to skip from a valid length to a hidden state, where I assume the paint event doesn't get called.  

I'm going to toss up a quick pydm PR referencing this issue

**Comment by tangkong** [comment]
closed by https://github.com/slaclab/pydm/pull/1036
