### ISSUE TITLE
Bug: Config GUI tag deletion crash (QWidget attribute .text)

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/atef#40]
## Expected Behavior

A crash has been reported on tag deletion

## Current Behavior

This may or may not be the right widget for it, but I tried to delete the last tag and crashed with the following:

```python
(atef) PC98125:atef klauer$ atef config
Traceback (most recent call last):
  File "/Users/klauer/Repos/atef/atef/bin/config.py", line 1197, in eventFilter
    if object.text():
AttributeError: 'QWidget' object has no attribute 'text'
```

_Originally posted by @klauer in https://github.com/pcdshub/atef/pull/28#discussion_r853314450_

**Comment by klauer** [comment]
I saw this one recently when redoing the device list widgets.

**Comment by ZLLentz** [comment]
I saw this also today while setting up the demo config
