### ISSUE TITLE
Bug: Config GUI tags have sizing issues

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/atef#41]
Sizing issue for `config_group.ui` for tags:

<img width="238" alt="image" src="https://user-images.githubusercontent.com/5139267/164060277-0e8227e3-a918-4240-8df1-464a874f2810.png">

_Originally posted by @klauer in https://github.com/pcdshub/atef/pull/28#discussion_r853316225_

**Comment by ZLLentz** [comment]
To-do: identify if this is platform-dependent and if there are specific sequences of actions that get us into this state.

**Comment by klauer** [comment]
Switching to `QToolButton` and using the default size constraints appears to be sufficient for this:

<img width="205" alt="image" src="https://user-images.githubusercontent.com/5139267/165173010-2f1d039e-64e7-4acf-b6c6-6b105ce94c04.png">

Designer:

<img width="670" alt="image" src="https://user-images.githubusercontent.com/5139267/165173177-aa00d6a1-8321-4cb2-8e72-0c970d9fecb6.png">

Note: I have not yet checked psbuild to compare
