### ISSUE TITLE
Prototype happi-related widgets for component filter/selection

### ISSUE THREAD

**Issue by klauer** [pcdshub/atef#59]
## Current Behavior
In the configuration GUI, you have to type the device name / component name directly and hope you have it correct.

## Proposed solution
Prototype a happi search widget that allows for - in order of priority:

1. Filtering/finding of happi devices, at least by name (some parts may exist already: https://github.com/pcdshub/happi/blob/master/happi/qt/model.py and require customization)
2. Viewing and selecting device components by name
3. Viewing the current state of the device - or via `ArchivedDevice`, at a selected time

This can be prototyped here and moved elsewhere as appropriate. At least (1) can belong in happi itself.

## Context
Configuration GUI discussions.

**Comment by klauer** [comment]
I'd like to poke around with this if you haven't started something similar already, @ZLLentz

**Comment by ZLLentz** [comment]
I have not started this yet and it's an important element of the v1 gui. Not strictly needed for alpha release but very important.
