### ISSUE TITLE
atef config: cancelled "open" at startup results in empty atef dialog

### ISSUE THREAD

**Issue by klauer** [pcdshub/atef#68]
## Steps to Reproduce (for bugs)
1. `atef config`
2. `open`
3. `cancel`
4. See screenshot

## Current Behavior
<img width="912" alt="image" src="https://user-images.githubusercontent.com/5139267/166565096-9a10a1e5-1837-45c4-b97e-e2c292a12325.png">

Confusing on macOS - much less so on Windows with its attached file menu. More details below.

**Comment by klauer** [comment]
This is 100% not a bug, but it's also not obvious on macOS what should be done. Why is that? Because the 'new' item hides in a separate menu at the top:

<img width="198" alt="image" src="https://user-images.githubusercontent.com/5139267/166565365-0a688b2c-bc67-4ab0-8961-13b4217beeea.png">

I think this could lead to confusion, and personally would just rather it show up as the "new config" dialog in general.

**Comment by ZLLentz** [comment]
Oh platform-dependent behavior! Always gets me.
Maybe we just... remove that close button...

**Comment by klauer** [comment]
Seems low priority overall. Removal of 'close' seems fine.
Down the line, we could possibly look into adding a toolbar with 'new/open/close' tool buttons with icons to make it look the same everywhere.

**Comment by ZLLentz** [comment]
In designer it actually looks like there's a toolbar in the main window body, fooling me completely.
![image](https://user-images.githubusercontent.com/10647860/166575056-dfac5248-41ac-4956-ab88-4293d306ed05.png)

**Comment by tangkong** [comment]
This is no longer relevant, now that we have a welcome splash screen 🎉
