### ISSUE TITLE
Feature: nominal value saving/restoring

### ISSUE THREAD

**Issue by klauer** [pcdshub/atef#86]
There is some discussion here:
* https://github.com/pcdshub/atef/discussions/14
* https://github.com/pcdshub/atef/discussions/4

This came up again during our short demo. We should re-evaluate the feature.

Special consideration should be made as to where such information might be stored - long-term, should it be atef or another database?

**Comment by klauer** [comment]
@tangkong I think it's been agreed that this is out of scope for atef. Close?

**Comment by tangkong** [comment]
Yep.  Configuration management is outside of ATEF's scope.  In the future we will want to integrate with whatever configuration manager tools exist/are developed.
