### ISSUE TITLE
Can't delete configurations unless the name is deleted first

### ISSUE THREAD

**Issue by christina-pino** [pcdshub/atef#98]
## Expected Behavior
Simply pressing the "Delete Configuration" button should remove the entry without having an empty name first

## Current Behavior
User has to remove the configuration name first, then delete

## Steps to Reproduce (for bugs)

1. Find a test config to delete
2. Press delete button and nothing happens
3. Delete entry name
4. Delete entry now works

## Context

It's inconvenient but not a priority

## Your Environment

source pcds_conda
My repo at /cds/home/c/cpino/atef
Andrew's repo at /cds/home/l/liggett1/atef

**Comment by ZLLentz** [comment]
This is intentional behavior to stop you from accidentally wiping your whole configuration.
Would it be better to keep this button enabled always, and add a confirmation dialog instead?

**Comment by klauer** [comment]
I think the current approach is neat, but this does show it could be confusing to new users. The confirmation dialog suggestion prior to deletion seems pretty intuitive.

**Comment by ZLLentz** [comment]
Yeah, let's go in that direction then- this also opens us to up to thinking about how we want to handle deleting checklist elements, etc. which currently all do the wonky "wipe the name and then click x"
